--CREATE DATABASE news_portal;
--\c news_portal
--
--CREATE TABLE departments(id SERIAL PRIMARY KEY, name VARCHAR,description VARCHAR,totalEmployees INT);
--
--CREATE TABLE users (id SERIAL PRIMARY KEY, name VARCHAR,position VARCHAR,role VARCHAR,department VARCHAR);
--
--CREATE TABLE news(id SERIAL PRIMARY KEY, title VARCHAR, description VARCHAR, type VARCHAR, author VARCHAR);